version: '3'
services:
  neo4j:
    image: neo4j:5.8.0
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server.memory.heap.initial_size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data: